### PR TITLE
Prevent unecessary selection of beta versions

### LINKED ISSUE #265: Beta version are selected by the solver again
A few months ago we added some logic to prevent the solver from selecting beta versions of the compiler but due to recent changes in the package and release model for OCaml betas, it's not working anymore and running `opam monorepo lock` without upper bound currently selects `4.14.0` beta versions.

### PR DESCRIPTION
**Pull request by NathanReb**
Fixes #265 !

Starting recently, beta versions of the compiler are released as `ocaml-base-compiler` and not `ocaml-variant` anymore. This had the side effect of making our solver pick beta versions if the constraints allowed it.

This fixes this issue but making the solver prefer regular versions over ones flagged with `avoid-version` in their opam metadata.

Such versions can still be selected when no regular version match the requirements.

### CODE REVIEW

File: lib/opam_solve.ml [hunk 1]
```diff
@@ -90,12 +90,22 @@ module Opam_monorepo_context (Base_context : BASE_CONTEXT) :
             else (version, Error Non_dune))
       versions
 
+  let sort_candidates versions =
```
Comment (Leonidas-from-XIV) [inline lib/opam_solve.ml:93]: I am not sure "sort" is the right term for it, given it doesn't really sort them but rather reorders them.

File: test/bin/compiler-beta.t/run.t [hunk 2]
```diff
@@ -0,0 +1,132 @@
+We have a simple project that only depends on OCaml
```
Comment (Leonidas-from-XIV) [inline test/bin/compiler-beta.t/run.t:1]: Since the code doesn't do anything compiler-specific (which is a good thing!) maybe it would make sense to just set up dummy packages? Dummy packages can have more monimal `opam` files that are easier to grasp and review.

File: test/bin/compiler-beta.t/run.t [hunk 3]
```diff
@@ -0,0 +1,132 @@
...
+
+  $ cat test.opam
```
Comment (Leonidas-from-XIV) [inline test/bin/compiler-beta.t/run.t:3]: I think printing the opam files entirely is not great, because the files are in Git anyway so the user can take a look at them. Rather I would suggest using the opam tool to print the interesting bit of the file, so the file can be modified if something unrelated needs to change without disrupting all the tests.

File: test/bin/compiler-beta.t/run.t [hunk 4]
```diff
@@ -0,0 +1,132 @@
...
+  ]
+
+We use the minimal repository which includes OCaml 4.13.1
+
+  $ gen-minimal-repo
+
+We also use an extra repository which happens to contain the packages of the
+ongoing beta release of OCaml 4.14.1
+
+  $ cat repo-with-beta-ocaml/packages/ocaml/ocaml.4.14.0/opam
```
Comment (Leonidas-from-XIV) [inline test/bin/compiler-beta.t/run.t:21]: Similar as above. This adds 80 lines of which possibly only like 71 is important.

File: test/bin/compiler-beta.t/run.t [hunk 5]
```diff
@@ -0,0 +1,132 @@
...
+     (enabled by default).
+     Please file a bug report at https://github.com/ocaml/opam-repository/issues"
+    {failure & jobs > 1}
+    "You can try installing again including --jobs=1
+     to force a sequential build instead."
+    {failure & jobs > 1 & opam-version >= "2.0.5"}
+  ]
+
+Our package does not define an upper bound on ocaml but the beta should not be
+selected by default if there exist another solution, therefore here the solver
```
Comment (Leonidas-from-XIV) [inline test/bin/compiler-beta.t/run.t:101]:
```suggestion
selected by default if there exists another solution, therefore here the solver
```

File: test/bin/compiler-beta.t/run.t [hunk 6]
```diff
@@ -0,0 +1,132 @@
...
+should pick 4.13.1:
```
Comment (Leonidas-from-XIV) [inline test/bin/compiler-beta.t/run.t:102]: This is fragile, it will break if a 4.13.2 is released.

**Review by Leonidas-from-XIV — COMMENTED** [review]
I think this is a nice solution and I especially like how flexible this is to not only work for the compiler but also for any other package (like alpha/beta/release candidate releases etc) that has that flag set. My comments are mostly about making the test better/more reliable.

File: test/bin/compiler-beta.t/run.t (hunk 2 above)
Comment (NathanReb) [reply test/bin/compiler-beta.t/run.t:1]: That would work but I like the fact that it shows it solves a real world problem, with real world metadata.

File: lib/opam_solve.ml (hunk 1 above)
Comment (Leonidas-from-XIV) [reply lib/opam_solve.ml:93]: Maybe `demote_candidates_to_avoid`? I would say it doesn't really sort them (because it requires the candidates to be sorted, otherwise we could conclude that the identity function is a sorting function that just requires the the input to be sorted), it more splits or partitions them.

File: test/bin/compiler-beta.t/run.t (hunk 3 above)
Comment (Leonidas-from-XIV) [reply test/bin/compiler-beta.t/run.t:3]: This file is short but it also includes a bunch of boilerplate, like the way the repos are set up which has nothing to do with the test and were it to change the test would need to be adapted for reasons that have nothing to do with the test itself.

File: test/bin/compiler-beta.t/run.t (hunk 2 above)
Comment (Leonidas-from-XIV) [reply test/bin/compiler-beta.t/run.t:1]: I agree in principle, but in practice I find these files very long and distracting to read (if there is something wrong, do you want to go through the whole file and try to understand what each of these stanzas does and how it interacts with the others?), so to review it I would need to read through every stanza, understand it, see if it is important etc. I would prefer the tests to concentrate on one aspect and show it working.

Kinda like we want to use minimal examples for tests, so reading and modifying these is easy instead of dealing with accidental complexity.

File: test/bin/compiler-beta.t/run.t (hunk 4 above)
Comment (NathanReb) [reply test/bin/compiler-beta.t/run.t:21]: You're right that printing those files entirely does not bring much value here. I'll remove that in favor of something shorter while still documenting those were taken from upstream opam repo.

File: test/bin/compiler-beta.t/run.t (hunk 6 above)
Comment (NathanReb) [reply test/bin/compiler-beta.t/run.t:102]: It won't because it uses our minimal repo, not upstream!

File: test/bin/compiler-beta.t/run.t (hunk 3 above)
Comment (NathanReb) [reply test/bin/compiler-beta.t/run.t:3]: I'll remove them but I don't see any reason why they would need to change since they are in fact very specific to this test and it's actually quite important to know what metadata will be used by the solver.

That's one of the reason why you can tell that it will always pick `4.13.1` below for instance.

File: test/bin/compiler-beta.t/run.t (hunk 2 above)
Comment (NathanReb) [reply test/bin/compiler-beta.t/run.t:1]: I think here it's important that it also checks that it works with the `ocaml` and `ocaml-base-compiler` split. If we change this test we can still break this behaviour while having the dummy tests pass. I'm happy to extract another test just for the avoid-version if you'd like but this test will stay as a regression test.

File: lib/opam_solve.ml (hunk 1 above)
Comment (NathanReb) [reply lib/opam_solve.ml:93]: Good name indeed, I'll change it!

**Comment by NathanReb** [comment]
Rebased!

File: CHANGES.md [hunk 7]
```diff
@@ -30,6 +30,8 @@
 
 - Fix a bug where a package which had a single version that built with dune and got selected by the solver
   would be reported has having no version building with dune. (#245, @Leonidas-from-XIV)
+- Fix the solver so it does not select beta versions of the compiler unless it
+  has to. (#269, @NathanReb)
```
Comment (Leonidas-from-XIV) [inline CHANGES.md:34]: Could you reword this a little? The current wording is a bit unclear, the reader is probably wondering "when does it have to then?". Specifying it like "it does not select beta version of the compiler unless forced by version constraints or on the command line" could be clearer.

**Review by Leonidas-from-XIV — APPROVED** [review]
Thanks for rebasing. I think this is an important fix, the code I'm :100: fine with. I'll leave it to you to reword the changelog entry to be a bit clearer, otherwise it is good to go :ship:

File: CHANGES.md (hunk 7 above)
Comment (NathanReb) [reply CHANGES.md:34]: Yeah sure, it is not very clear indeed!

Comment (NathanReb) [reply CHANGES.md]: I think it's better know so I'll merge don't hesitate if you think it's still not clear enough, I'll be happy to update it separately!

We should do a brief review of the changelog before the release by the way to make sure everything is clear.

Comment (Leonidas-from-XIV) [reply CHANGES.md]: A review sounds good. Sometimes the entries make sense when writing the PR but afterwards it might be less so.
